name: CI

on: [push]

jobs:
  build:
    name: Startup
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs_version:
          - snapshot
        include:
          - os: macos-latest
            emacs_version: snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2
    - name: Check startup
      run: make startup
